# Generated by Django 5.0.6 on 2024-07-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_foodquantity_post_foodtype_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='foodQUantity',
            new_name='foodQuantity',
        ),
    ]
