# Generated by Django 5.0.6 on 2024-07-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_locx_profile_locy_consumer_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_consumer', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_producer', to='api.profile'),
        ),
    ]
